# Generated by Django 4.2.7 on 2024-01-13 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carmodel',
            name='discription',
            field=models.TextField(blank=True),
        ),
    ]
