# Generated by Django 4.2.7 on 2024-03-17 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0006_alter_carmodel_ordered_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carmodel',
            name='ordered_by',
        ),
    ]
